import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
	filter: {
		backgroundColor: '#161D46',
		flex: 1,
		width: '100%',
		paddingTop: 40,
	},
	title: {
		color: '#ffffff',
		fontSize: 35,
		marginHorizontal: 30,
		marginLeft: 87,
		alignItems: 'center',
		fontFamily: 'JosefinSansRegular',
	},
	scrollView: {
		flex: 1,
		marginTop: 10,
	},
	checklistContainer: {
		marginBottom: 20,
		marginLeft: 10,
		marginRight: 10,
	},
	checklistTitle: {
		color: '#ffffff',
		fontSize: 20,
		marginBottom: 10,
		marginLeft: 20,
		fontFamily: 'JosefinSansRegular',
	},
	checklistItem: {
		flexDirection: 'row',
		alignItems: 'center',
		backgroundColor: '#1E2A4A',
		padding: 10,
		margin: 5,
		borderRadius: 5,
	},
	checkbox: {
		width: 20,
		height: 20,
		marginRight: 10,
		backgroundColor: '#ffffff',
		borderRadius: 3,
		borderWidth: 1,
		borderColor: '#000',
		alignItems: 'center',
		justifyContent: 'center',
	},
	checkedCheckbox: {
		backgroundColor: '#4CAF50',
	},
	checkmark: {
		color: '#ffffff',
	},
	checklistItemText: {
		color: '#ffffff',
		fontSize: 16,
		flex: 1,
		fontFamily: 'JosefinSansRegular',
	},
	addButton: {
		backgroundColor: '#5050B2',
		padding: 10,
		margin: 5,
		borderRadius: 5,
		alignItems: 'center',
	},
	addButtonLabel: {
		color: '#ffffff',
		fontSize: 16,
		fontFamily: 'JosefinSansRegular',
	},
	textInput: {
		backgroundColor: '#ffffff',
		padding: 10,
		margin: 5,
		borderRadius: 5,
		fontFamily: 'JosefinSansRegular',
	},
	deleteButtonText: {
		color: '#FFFFFF',
		fontSize: 16,
		fontFamily: 'JosefinSansRegular',
	},
	deleteButtonIcon: {
		fontSize: 26,
		marginTop: 5,
		fontFamily: 'JosefinSansRegular',
	},
	addChecklistButton: {
		backgroundColor: '#5050B2',
		padding: 10,
		margin: 10,
		borderRadius: 5,
		alignItems: 'center',
	},
	addChecklistButtonText: {
		color: '#ffffff',
		fontSize: 16,
		fontFamily: 'JosefinSansRegular',
	},
	checklistHeader: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		marginBottom: 10,
	},
	deleteButton: {
		padding: 1,
		marginRight: 5,
		marginBottom: 10,
	},

	centeredView: {
		flex: 1,
		justifyContent: 'center',
		alignItems: 'center',
		paddingTop: 22,
		backgroundColor: 'rgba(0,0,0,0.5)',
	},
	modalView: {
		margin: 20,
		backgroundColor: '#5050B2',
		borderRadius: 10,
		padding: 35,
		alignItems: 'center',
		shadowColor: '#000',
		shadowOffset: {
			width: 0,
			height: 2,
		},
		shadowOpacity: 10,
		shadowRadius: 4,
		elevation: 5,
	},
	modalTitle: {
		marginBottom: 20,
		fontSize: 24,
		textAlign: 'center',
		color: 'white',
		fontFamily: 'JosefinSansRegular',
	},
	modalTextInput: {
		height: 40,
		width: 200,
		borderColor: 'white',
		color: 'white',
		borderWidth: 1,
		marginBottom: 20,
		paddingHorizontal: 10,
		borderRadius: 5,
		textAlign: 'center',
		fontFamily: 'JosefinSansRegular',
	},
	modalButton: {
		backgroundColor: 'white',
		borderRadius: 5,
		padding: 10,
		elevation: 2,
		marginBottom: 10,
	},
	modalButton1: {
		backgroundColor: '#C23434',
		borderRadius: 5,
		padding: 10,
		elevation: 2,
		marginBottom: 10,
	},
	modalButtonText: {
		color: 'black',
		textAlign: 'center',
		fontFamily: 'JosefinSansRegular',
	},
	modalButtonText1: {
		color: 'white',
		textAlign: 'center',
		fontFamily: 'JosefinSansRegular',
	},
});
